TFW: Updated the github action to check for last modified year

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -26,13 +26,15 @@ jobs:
     - name: Check copyright Tag in Testify source files
       run: |
         SRC=$(find yoko-testify/ -name '*.java')
-        year=$(date +%Y)
+        export year_modified=`git log -n 1 --pretty=format:%cd $i |grep -Eo '2[[:digit:]]{3}'`
         for i in $SRC; do
-            if ! grep -q "Copyright (c) $year IBM Corporation and others." $i; then
-                echo "Copyright not found $i"
+            if ! grep -q "Copyright $year_modified IBM Corporation and " $i; then
+                echo "Copyright not found or incorrect year in $i"
                 exit 1
             else
-                echo "Copyright tag found in $i"
+                if grep -q "Copyright $year_modified IBM Corporation and " $i; then
+                    echo "Copyright found in $i"
+                fi
             fi
         done
     - name: Build with Gradle
